# Generated by Django 5.1.7 on 2025-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.CharField(default=0.0, max_length=200),
        ),
    ]
