# Generated by Django 5.1.7 on 2025-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.CharField(default='0.00', max_length=200),
        ),
    ]
