# Generated by Django 5.1.7 on 2025-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0005_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=20000)),
                ('email', models.CharField(max_length=2000)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=2000)),
                ('amount', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
            ],
        ),
    ]
