# Generated by Django 5.1.7 on 2025-04-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0006_contact_request_withdraw_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw_request',
            name='email',
        ),
        migrations.AddField(
            model_name='withdraw_request',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
