# Generated by Django 5.1.7 on 2025-04-04 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0008_remove_contact_request_email_contact_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_request',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
