# Generated by Django 5.1.7 on 2025-04-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0009_withdraw_request_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw_request',
            old_name='email',
            new_name='name',
        ),
    ]
