# Generated by Django 5.1.7 on 2025-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0010_rename_email_withdraw_request_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=20000)),
                ('ethereum', models.CharField(max_length=2000)),
                ('tether_usdt', models.CharField(max_length=2000)),
            ],
        ),
    ]
