# Generated by Django 5.1.7 on 2025-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0011_crypto_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
